In [30]:
# numpy
import numpy as np

arr=np.array([3,33,25])
print(arr)
print(type(arr))
print(arr.ndim)

[ 3 33 25]
<class 'numpy.ndarray'>
1


In [2]:
print(arr.shape)
      

(3,)


In [5]:
print(arr[0],arr[1],arr[2])

3 33 25


In [21]:
arr[0]=20
print(arr)

[20 33 25]


# TWO DIMENSTIONAL ARRAY

In [19]:
arr1=np.array([[12,15,14],[1,5,3]])
print(arr1)
print("the shape is 2 row and 3 columns:",arr1.shape)
print(arr1[0,0], arr1[1,0],arr1[1,2])

[[12 15 14]
 [ 1  5  3]]
the shape is 2 row and 3 columns: (2, 3)
12 1 3


In [ ]:
# Array using different fuction

In [22]:
# 2*2 matrix with 0 value
ex1=np.zeros((2,2))
print(ex1)

[[0. 0.]
 [0. 0.]]


In [23]:
# 2*2 matrix with 9.0 value
ex2=np.full((2,2),9.0)
print(ex2)

[[9. 9.]
 [9. 9.]]


In [25]:
# digonal matrix
ex3=np.eye(2,2)
print(ex3)

[[1. 0.]
 [0. 1.]]


In [26]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)


[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [27]:
ex4=np.ones((1,2))
print(ex4)

[[1. 1.]]


In [28]:
print(ex4.shape)
print()
print(ex4[0,0])

(1, 2)

1.0


which means we nedd two indexes to access an element

In [29]:
ex5= np.random.random((2,2))
print(ex5)

[[0.8093457  0.89838366]
 [0.53307279 0.73907066]]


# Array Indexing

In [31]:
arr3=np.array([[1,2,3,4],[7,8,9,6],[4,5,6,3]])
print(arr3)

[[1 2 3 4]
 [7 8 9 6]
 [4 5 6 3]]


In [48]:
s=arr3[0:2,1:3]
print(s)

[[  2   3]
 [100 100]]


In [47]:
#s=arr3[1:2,1:3]
#print(s)

In [49]:
print("before",arr3[0,1])
s[0,1]=100
print("after",arr3[0,1])
print(arr3)
print(s)


before 2
after 2
[[  1   2 100   4]
 [  7 100 100   6]
 [  4   5   6   3]]
[[  2 100]
 [100 100]]


In [43]:
row_rank1=arr3[1,:]
print(row_rank1,row_rank1.shape)

[  7 100 100   6] (4,)


In [44]:
row_rank1=arr3[1:2,:]
print(row_rank1,row_rank1.shape)

[[  7 100 100   6]] (1, 4)


In [53]:

print(arr3)
print()
col_rank=arr3[:,1]
col_rank1=arr3[:,1:2]
print(col_rank,col_rank.shape)
print()
print(col_rank1,col_rank1.shape)


[[  1   2 100   4]
 [  7 100 100   6]
 [  4   5   6   3]]

[  2 100   5] (3,)

[[  2]
 [100]
 [  5]] (3, 1)


In [65]:
arr4=np.array([[1,2,3,4],[7,8,9,6],[4,5,6,3],[10,20,30,40]])
print(arr4)

[[ 1  2  3  4]
 [ 7  8  9  6]
 [ 4  5  6  3]
 [10 20 30 40]]


In [66]:
# creating array of indices
col_ind=np.array([0,1,2,0])

print("\n coloum indices picked ",col_ind)

row_ind=np.arange(4)
print("\n Roe indices picked ",row_ind)


 coloum indices picked  [0 1 2 0]

 Roe indices picked  [0 1 2 3]


In [67]:
for row,col in zip (row_ind,col_ind):
    print(row,",",col)

0 , 0
1 , 1
2 , 2
3 , 0


In [68]:
print(arr4)
print()
print("after ",arr4[row_ind,col_ind])

[[ 1  2  3  4]
 [ 7  8  9  6]
 [ 4  5  6  3]
 [10 20 30 40]]

after  [ 1  8  6 10]


In [75]:
arr4[row_ind,col_ind]+=10000
print(arr4)


[[10001     2     3     4]
 [    7 10008     9     6]
 [    4     5 10006     3]
 [10010    20    30    40]]


In [70]:
arr5=np.array([[11,12],[21,22],[31,32]])
print(arr5)

[[11 12]
 [21 22]
 [31 32]]


In [71]:
filter=(arr5>15)
filter

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [72]:
print(arr5[filter])

[21 22 31 32]


In [73]:
arr5[arr5>15]

array([21, 22, 31, 32])

In [74]:
arr5[arr5%2==0]+=100
print(arr5)

[[ 11 112]
 [ 21 122]
 [ 31 132]]
